### PR TITLE
Switch to version 8.0.303 of the .NET sdk

### PR DESCRIPTION
**Pull request by dlemstra**
This PR updates the sdk to version 8.0.303.

### CODE REVIEW

**Comment by joelverhagen** [comment]
FYI I changed base branch to `dev` since that's where we put non-hotfixes. I will get this through the CI.

**Comment by erdembayar** [comment]
Thank you for your contributions, it looks are internal pipeline is failing. We need to make more changes in our internal CI pipeline to accept this change. We have done it recently for one of our repo https://github.com/NuGet/NuGetGallery/pull/9986

**Comment by joelverhagen** [comment]
Thanks @erdembayar, I updated the CI Pipeline (the one linked is not YAML yet) and I will update the internal release pipelines YAML like you did for Gallery.

**Comment by joelverhagen** [comment]
FYI I pushed a commit for using .NET 8 in search service. Build was failing otherwise.

**Review by joelverhagen — APPROVED** [review]

**Pull request merged**
