### PR TITLE
Edit&history job: support file system gallery.

### PR DESCRIPTION
**Pull request by Yustos**
Add file system packages store support (without Azure) for editing,history and package rewrite job.
Job run example:
`HandlePackageEdits.exe -PackageDatabase "..." -StorageType FileSystem -BackupStorage "c:\backups" -SourceStorage "c:\packages"`

### CODE REVIEW

**Comment by Yustos** [comment]
And there is some lapse in Nuget Gallery deploy documentation.
Packages editing is gallery is not fully functional without HandlePackageEdits job. After save, i see pending edit warning, and it never hide and no history recorded.

The only way i found missing job is comment in Gallery sources:
`
// Note: EditPackageRequests are completed asynchronously by the worker role.
`
Then i find job in another repository.

**Comment by Yustos** [comment]
And I can not test work in cloud (no account).

**Comment by chenriksson** [comment]
Hi @Yustos,

Thanks for the contribution and suggested improvements!

We've recently created the [NuGet.Services.Storage](https://github.com/NuGet/ServerCommon/tree/master/src/NuGet.Services.Storage) package to handle storage abstractions including Azure and file storage, which we are moving towards with our backend jobs. 

For this PR, I would recommend we move the Storage abstractions to [ServerCommon](https://github.com/NuGet/ServerCommon) with the other shared code. IFileStorage can be combined with the existing IStorage interface, and the snapshot support would need to be introduced.

Thanks,
Christy

**Comment by chuotnhat1985** [comment]
Hi @chenriksson,

How to user Nuget.Services.Storage in NugetGallery. I'm facing the problem when editing package. There is no effected into database. I storaged package in Hard Drive.

**Comment by joelverhagen** [comment]
The `HandlePackageEdits` job has long since been deprecated. Packages on NuGet.org (and by extension NuGetGallery + jobs) are considered immutable.

**Pull request closed without merging**
