### PR TITLE
Package source mapping

### PR DESCRIPTION
**Pull request by agr**
Adding package source mapping to address some build warnings.
The list is based on the Gallery [one](https://github.com/NuGet/NuGetGallery/blob/0c62a31f83c699beb4797f620a68b62c76eb585c/NuGet.config#L15).

### CODE REVIEW

**Review by joelverhagen — APPROVED** [review]
🚀

**Comment by mariaghiondea** [comment]
@agr is this still needed?

**Review by erdembayar — APPROVED** [review]

**Comment by erdembayar** [comment]
@agr Did you use https://www.nuget.org/packages/NuGet.PackageSourceMapper for generating mapping?

**Review by advay26 — APPROVED** [review]

**Comment by agr** [comment]
@erdembayar no, just tried building repeatedly adding more packages to the list until it actually built.

**Comment by erdembayar** [comment]
> @erdembayar no, just tried building repeatedly adding more packages to the list until it actually built.

Please try that one next time, it'll generate solution in less than 1 min.

**Pull request merged**
