### PR TITLE
NuGetGallery.Core update with new storage SDK

### PR DESCRIPTION
**Pull request by agr**
Progress on https://github.com/NuGet/Engineering/issues/5335.
NuGet.Jobs counterpart of https://github.com/NuGet/NuGetGallery/pull/10018

NuGetGallery.Core update to new storage SDK brought some API changes. Mostly replacing previously exposed underlying SDK types with abstractions provided by NuGetGallery.Core.

Tested the following jobs after update (those use NuGetGallery.Core pretty extensively):
* Catalog2Registration;
* Validation.Orchestrator;
* Validation.Symbol.Job.

Besides that, verified, that some other jobs that rely on feature flag functionality (which again uses NuGetGallery.Core abstractions), still have that functionality working.

### CODE REVIEW

**Review by drewgillies — APPROVED** [review]

**Review by erdembayar — DISMISSED** [review]
🚢

**Comment by erdembayar** [comment]
@agr 
I realized constructor of `CloudBlobLeaseService.cs` still depends on old `Microsoft.WindowsAzure.Storage.Blob`. Do we expect another PR or could it be fixed in this PR?

**Comment by agr** [comment]
@erdembayar it can be fixed separately, it's not really related to NuGetGallery.Core update.

**Review by erdembayar — DISMISSED** [review]
👏

**Comment by erdembayar** [comment]
@agr 
When do you merge this PR? I have another PR built upon this one.

**Review by drewgillies — APPROVED** [review]

**Review by erdembayar — APPROVED** [review]

**Pull request merged**
