### PR TITLE
fixFor3472

### PR DESCRIPTION
**Pull request by cristinamanum**

### CODE REVIEW

**Comment by skofman1** [comment]
There are several jobs in the statistics pipeline, we need to update them as well to use dbo, to prevent similar issues down the line.

**Comment by xavierdecoster** [comment]
Did you verify this line still works as expected? 
https://github.com/NuGet/NuGet.Jobs/blob/81fa007ca528a64d1a684878e9915f760a26c3c5/src/Stats.ImportAzureCdnStatistics/LogFileProcessor.cs#L93

**Comment by cristinamanum** [comment]
Hi Xavier, the PR has the mentioned change. Please let me know if the change is not enough.

**Comment by xavierdecoster** [comment]
Nevermind, overlooked :) Fix is good!

**Pull request merged**
