### PR TITLE
Deployment scripts for SupportRequest.Notifications job

### PR DESCRIPTION
**Pull request by xavierdecoster**
The PR contains an update to `build.ps1` to ensure the new job is compiled and packaged, and the package contains two separate startup scripts for the same job with different parameters.

OctopusDeploy pipeline created under `Jobs - Send support request notifications`. As discussed offline with @skofman1, we'll only target `PROD` environment to avoid noise on `DEV` and `INT`.

### CODE REVIEW

**Comment by scottbommarito** [comment]
Isn't there a `PreDeploy` and `PostDeploy` script that needs to be included with this? I imagine it will need to be a different script than we usually use because we plan to use the Task Scheduler for this job.

**Comment by xavierdecoster** [comment]
No pre/post deploy needed exactly for that reason. Those scripts were only removing the windows service pre-deployment, and installing the windows service post-deployment. This is no windows service.

**Comment by skofman1** [comment]
How does Octopus create a new scheduled task? Is it a step you add there, or an additional script you will add to the code?

**Comment by xavierdecoster** [comment]
@skofman1 automation is possible using PowerShell, however, I'm wondering if we should put effort in doing so. Configuring the scheduled tasks is a one-time setup. Future deployments will simply replace the executable and the scripts in this PR. What do you think?

**Comment by skofman1** [comment]
@xavierdecoster , completely agreed, no further automation required.

**Pull request merged**
